export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as HowItWorks } from './HowItWorks'
export { default as Comparison } from './Comparison'
export { default as OpenSource } from './OpenSource'
export { default as CTAFooter } from './CTAFooter'
